site_name: Case ML Engineer Pleno
repo_url: https://github.com/rafael-asafe/case_ml_engineer_pleno
repo_name: rafael-asafe/repo
edit_uri: tree/main/docs

theme:
  name: material
  palette:
    primary: green
    accent: light green
  language: pt-BR

extra_css:
  - stylesheets/extra.css

watch:
  - docs

nav:
  - Início: index.md
  - Parte 1 — ETL PokeAPI:
      - Como executar: projetos/analise_dado_pokeapi/analise_dados_pokeapi.md
      - Documentação Técnica: projetos/analise_dado_pokeapi/documentação.md
      - Planejamento e Desenvolvimento: projetos/analise_dado_pokeapi/desenvolvimento.md
  - Parte 2 — Microserviço NER:
      - Como iniciar: projetos/micro_servico_model_serving.md
      - Arquitetura: projetos/nre_service/arquitetura.md
      - Referência da API: projetos/nre_service/api_reference.md
      - Configuração: projetos/nre_service/configuracao.md
      - Desenvolvimento: projetos/nre_service/desenvolvimento.md